spring.application.name=auth-service

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/khaaliroom_auth
spring.datasource.username=postgres
spring.datasource.password=REMOVED_SECRET
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=change-this-to-a-long-random-secret-key
# 1 Hour
jwt.expiration=3600000
# 30 days
jwt.refresh-expiration-minutes=43200
# User service
user-service.url=http://localhost:8082
internal.service.secret=change-this-internal-secret